import '../../domain/entities/account_entity.dart';
import '../../domain/enums/account_type_enum.dart';
import '../../domain/patterns/states/account_state_factory.dart';

class AccountModel extends AccountEntity {
  AccountModel({
    required int id,
    required String publicId,
    required int userId,
    required int? parentId,
    required AccountTypeEnum type,
    required double balance,
    required String state,
    String? dailyLimit,
    String? monthlyLimit,
    String? closedAt,
    required String createdAt,
    required String updatedAt,
  }) : super(
    id: id,
    publicId: publicId,
    userId: userId,
    parentId: parentId,
    type: type,
    balance: balance,
    state: AccountStateFactory.from(state),
    dailyLimit: dailyLimit,
    monthlyLimit: monthlyLimit,
    closedAt: closedAt != null ? DateTime.parse(closedAt) : null,
    createdAt: DateTime.parse(createdAt),
    updatedAt: DateTime.parse(updatedAt),
  );

  factory AccountModel.fromJson(Map<String, dynamic> json) {
    return AccountModel(
      id: json['id'] as int? ?? 0,
      publicId: json['public_id'] as String? ?? '',
      userId: json['user_id'] as int? ?? 0,
      parentId: json['parent_id'] as int?,
      type: AccountTypeEnum.fromValue(json['type'] as String? ?? 'savings'),
      balance: (json['balance'] as num? ?? 0).toDouble(),
      state: json['state'] as String? ?? 'active',
      dailyLimit: json['daily_limit']?.toString(),
      monthlyLimit: json['monthly_limit']?.toString(),
      closedAt: json['closed_at'] as String?,
      createdAt: json['created_at'] as String? ?? DateTime.now().toIso8601String(),
      updatedAt: json['updated_at'] as String? ?? DateTime.now().toIso8601String(),
    );
  }

  Map<String, dynamic> toJson() {
    return {
      'id': id,
      'public_id': publicId,
      'user_id': userId,
      'parent_id': parentId,
      'type': type.value,
      'state': state.name,
      'balance': balance,
      'daily_limit': dailyLimit,
      'monthly_limit': monthlyLimit,
      'closed_at': closedAt?.toIso8601String(),
      'created_at': createdAt.toIso8601String(),
      'updated_at': updatedAt.toIso8601String(),
    };
  }

  // Factory method for creating new account
  factory AccountModel.createNew({
    required int userId,
    required AccountTypeEnum type,
    double initialBalance = 0.0,
    String? dailyLimit,
    String? monthlyLimit,
  }) {
    return AccountModel(
      id: 0, // Will be assigned by backend
      publicId: '', // Will be generated by backend
      userId: userId,
      parentId: null, // Will be set by backend
      type: type,
      balance: initialBalance,
      state: 'active',
      dailyLimit: dailyLimit,
      monthlyLimit: monthlyLimit,
      closedAt: null,
      createdAt: DateTime.now().toIso8601String(),
      updatedAt: DateTime.now().toIso8601String(),
    );
  }

  // Copy with method
  AccountModel copyWith({
    int? id,
    String? publicId,
    int? userId,
    int? parentId,
    AccountTypeEnum? type,
    double? balance,
    String? state,
    String? dailyLimit,
    String? monthlyLimit,
    String? closedAt,
    String? createdAt,
    String? updatedAt,
  }) {
    return AccountModel(
      id: id ?? this.id,
      publicId: publicId ?? this.publicId,
      userId: userId ?? this.userId,
      parentId: parentId ?? this.parentId,
      type: type ?? this.type,
      balance: balance ?? this.balance,
      state: state ?? this.state.name,
      dailyLimit: dailyLimit ?? this.dailyLimit,
      monthlyLimit: monthlyLimit ?? this.monthlyLimit,
      closedAt: closedAt ?? this.closedAt?.toIso8601String(),
      createdAt: createdAt ?? this.createdAt.toIso8601String(),
      updatedAt: updatedAt ?? this.updatedAt.toIso8601String(),
    );
  }
}